apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: newnode
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: newnode 
  name: newnode
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: newnode 
